[tool.azure-sdk-build]
breaking = false
mypy = false
pyright = false
type_check_samples = false
verifytypes = false

[packaging]
package_name = "azure-mgmt-hybridnetwork"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Hybrid Network Management"
package_doc_id = ""
is_stable = true
is_arm = true
title = "HybridNetworkManagementClient"
need_msrestazure = false
need_azuremgmtcore = true
sample_link = ""
exclude_folders = ""
